services:
  bot:
    container_name: bot
    image: discord/bot:latest
    build: .
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - ./data:/app/data
    working_dir: /app
    command: python -m src
