[tool.mypy]
python_version = "3.10"
exclude = [
    "collections",
    "tests",
    "venv",
]
ignore_missing_imports = true

[tool.ruff]
lint.select = ["E", "F", "W", "C90", "S", "I", "N", "UP"]
lint.ignore = ["N999"]
lint.fixable = ["ALL"]
lint.unfixable = []
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 117
target-version = "py310"
fix = true

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["SLF001"]
".github/*" = ["INP001"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.black]
line-length = 117
target-version = ["py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.bandit]
exclude_dirs = ["venv",]
skips = ["B101",]
